### ISSUE TITLE
Commit privilege and Spark package maintenance

### ISSUE THREAD

**Issue by ntietz** [tbfenet/spark-jms-receiver#3]
I recently received an email asking for usage examples and for support for another version of Spark (1.4.1). It would probably be good to support 1.4.x, 1.6.x, and 2.0.x as these are the common versions right now. I would also like to contribute usage examples.

I'm sure you've got a lot on your plate. Is there a way you could give me commit privileges for this repo, and some way to update the spark package? Then we can get these changes in quickly.

**Comment by tbfenet** [comment]
Sure. I am on a business trip to Paris at the moment and have intermittent internet access. Need remember how the spark packages thing works. It has been a while since I set it up

**Comment by ntietz** [comment]
I totally understand! I hope your trip's not too hectic and you get to enjoy the city a little bit :)

If you want me to be able to publish releases, I think I have to have admin privileges on the repo (that's what the command line is telling me, anyway). I understand if you have reservations about doing that, or just generally want to control releases yourself.

If you do get me admin privileges, and also if that's all that is needed to let me do releases, then I should have a release out this weekend to support 1.4.x, 1.6.x, and 2.0.x.

**Comment by ntietz** [comment]
@tbfenet any status update? Hoping to get this into spark-packages.org soon. If you don't want to maintain it, I can fork it and become the maintainer, if you'd prefer that.

**Comment by tbfenet** [comment]
Think it should be up there now. For some reason It did not work on Monday night but worked last night.

**Comment by ntietz** [comment]
Sorry I didn't respond to this quicker (was swamped with work, partially because getting it uploaded unblocked me ;) ). Thanks for getting that in, it was invaluable for us.
