### ISSUE TITLE
Passing user credentials

### ISSUE THREAD

**Issue by ghost** [tbfenet/spark-jms-receiver#5]
Successfully implemented receiver client code using
   val msgs = JmsStreamUtils.createSynchronousJmsQueueStream(ssc, MQConsumerFactory(host, port.toInt, qm, qn, user, credentials),
                                                                 converter,
                                                                  1000,
                                                                  1.second,
                                                                  10.seconds,
                                                                  StorageLevel.MEMORY_AND_DISK_SER
                                                                 )
      Here, the user and credentials passing are blank. For an authorization enabled MQ cluster, passing user name and password is returning AUTHORIZATION ERROR for the specific queue manager and queue name. Here passing the username and password as plain text. Please advise.

And, is there a way I can pass MQ channel to the ConsumerFactory? Currently the queue manager and queue name are being passed to this.

**Comment by tbfenet** [comment]
MQConsumerFactory is presumably one of your classes are you setting credentials in makeConnection metthod? see. JndiMessageConsumerFactory . 
You could using jndi to setup consumer.

**Comment by ghost** [comment]
No. I'm directly getting connected to MQ with JmsStreamUtils.createSynchronousJmsQueueStream() by passing queue manager and queue name.

**Comment by tbfenet** [comment]
MQConsumerFactory  in not part of spark-jms-receiver and presumably is an implementation of MessageConsumerFactory which is. This is where any MQ specific code would be and where problems with authorisation will probably be. spark-jms-receiver is independent of any particular implementation of JMS and I don't think JMS has a concept of channels. If you have access to MQConsumerFactory code you should be able to modify it to pass  a channel.

**Comment by ghost** [comment]
I could achieve passing channel by customizing MQConsumerFactory to accept channel as param. Thanks for support. Closing this issue.
